# Generated by Django 6.0.5 on 2026-06-11 18:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CursoLiberado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_liberacao', models.DateField(default=django.utils.timezone.now)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liberacoes', to='core.curso')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos_liberados', to='core.tecnico')),
            ],
            options={
                'verbose_name': 'Curso liberado',
                'verbose_name_plural': 'Cursos liberados',
                'unique_together': {('tecnico', 'curso')},
            },
        ),
    ]
