# Generated by Django 6.0.5 on 2026-06-13 18:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tecnico_usuario_cursoliberado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nota_minima',
            field=models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='EtapaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('texto', 'Conteúdo em texto'), ('video', 'Vídeo'), ('teste', 'Teste'), ('prova', 'Prova final')], max_length=10)),
                ('ordem', models.PositiveIntegerField()),
                ('conteudo', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='core.curso')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProgressoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('em_andamento', 'Em andamento'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='nao_iniciado', max_length=20)),
                ('tentativa_atual', models.PositiveIntegerField(default=1)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='core.curso')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='core.tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentativa', models.PositiveIntegerField(default=1)),
                ('concluida_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='core.etapacurso')),
                ('progresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_concluidas', to='core.progressocurso')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='core.etapacurso')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('correta', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='core.questao')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TentativaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tentativa_curso', models.PositiveIntegerField()),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aprovado', models.BooleanField(default=False)),
                ('realizada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='core.etapacurso')),
                ('progresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.progressocurso')),
            ],
            options={
                'ordering': ('-realizada_em',),
            },
        ),
        migrations.AddConstraint(
            model_name='etapacurso',
            constraint=models.UniqueConstraint(fields=('curso', 'ordem'), name='etapa_ordem_unica_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='progressocurso',
            constraint=models.UniqueConstraint(fields=('tecnico', 'curso'), name='progresso_unico_por_tecnico_curso'),
        ),
        migrations.AddConstraint(
            model_name='progressoetapa',
            constraint=models.UniqueConstraint(fields=('progresso', 'etapa', 'tentativa'), name='conclusao_etapa_unica_por_tentativa'),
        ),
    ]
