# Generated by Django 6.0.5 on 2026-07-09 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def criar_empresa_padrao(apps, schema_editor):
    Empresa = apps.get_model("core", "Empresa")
    Tecnico = apps.get_model("core", "Tecnico")

    empresa, _ = Empresa.objects.get_or_create(
        nome="Sem Parar",
        defaults={
            "responsavel": "Administrador",
            "ativa": True,
        },
    )
    Tecnico.objects.filter(empresa__isnull=True).update(empresa=empresa)


def desfazer_empresa_padrao(apps, schema_editor):
    Tecnico = apps.get_model("core", "Tecnico")
    Tecnico.objects.update(empresa=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_curso_nota_minima_etapacurso_progressocurso_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, unique=True)),
                ("documento", models.CharField(blank=True, max_length=30)),
                ("responsavel", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("ativa", models.BooleanField(default=True)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.AddField(
            model_name="tecnico",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tecnicos",
                to="core.empresa",
            ),
        ),
        migrations.RunPython(criar_empresa_padrao, desfazer_empresa_padrao),
        migrations.AlterField(
            model_name="tecnico",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tecnicos",
                to="core.empresa",
            ),
        ),
    ]
