# Generated by Django 6.0.5 on 2026-07-09 15:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adiciona_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('operacional', 'Responsável operacional'), ('editor_cursos', 'Editor de cursos')], default='operacional', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='core.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsabilidades_empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsável da empresa',
                'verbose_name_plural': 'Responsáveis das empresas',
                'ordering': ('empresa__nome', 'usuario__username'),
                'constraints': [models.UniqueConstraint(fields=('empresa', 'usuario', 'papel'), name='responsavel_empresa_papel_unico')],
            },
        ),
    ]
