# Generated by Django 6.0.5 on 2026-07-09 15:45

from django.db import migrations, models


def preencher_codigos_certificado(apps, schema_editor):
    ConclusaoTreinamento = apps.get_model("core", "ConclusaoTreinamento")

    for conclusao in ConclusaoTreinamento.objects.filter(codigo_certificado=""):
        conclusao.codigo_certificado = f"CERT-{conclusao.pk:08X}"
        conclusao.save(update_fields=["codigo_certificado"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_adiciona_responsavel_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="conclusaotreinamento",
            name="codigo_certificado",
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.RunPython(preencher_codigos_certificado, migrations.RunPython.noop),
    ]
