# Generated by Django 6.0.5 on 2026-07-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_adiciona_codigo_certificado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conclusaotreinamento",
            name="codigo_certificado",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),
    ]
