# Generated by Django 6.0.5 on 2026-07-14 00:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_torna_codigo_certificado_unico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('cadastro', 'Cadastro'), ('edicao', 'Edicao'), ('status', 'Status'), ('importacao', 'Importacao'), ('liberacao', 'Liberacao'), ('convite', 'Convite')], max_length=20)),
                ('alvo_tipo', models.CharField(max_length=80)),
                ('alvo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('alvo_repr', models.CharField(blank=True, max_length=255)),
                ('detalhes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='core.empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoria',
                'verbose_name_plural': 'Eventos de auditoria',
                'ordering': ('-criado_em', '-id'),
            },
        ),
    ]
