# Generated by Django 6.0.5 on 2026-07-19 00:11

from django.db import migrations, models


def vincular_cursos_existentes_a_sem_parar(apps, schema_editor):
    Curso = apps.get_model("core", "Curso")
    Empresa = apps.get_model("core", "Empresa")
    sem_parar = Empresa.objects.filter(nome__iexact="Sem Parar").first()
    if not sem_parar:
        return

    for curso in Curso.objects.all():
        curso.empresas_disponiveis.add(sem_parar)


def desvincular_cursos_existentes(apps, schema_editor):
    Curso = apps.get_model("core", "Curso")
    for curso in Curso.objects.all():
        curso.empresas_disponiveis.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventoauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='empresas_disponiveis',
            field=models.ManyToManyField(blank=True, related_name='cursos_disponiveis', to='core.empresa', verbose_name='empresas com acesso'),
        ),
        migrations.RunPython(
            vincular_cursos_existentes_a_sem_parar,
            desvincular_cursos_existentes,
        ),
    ]
