# Generated by Django 6.0.5 on 2026-07-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_produto_empresa_contexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='material_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cursos/pdfs/', verbose_name='PDF do curso'),
        ),
    ]
