from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="core/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "senha/esqueci/",
        auth_views.PasswordResetView.as_view(
            template_name="core/password_reset_form.html",
            email_template_name="core/emails/password_reset_email.txt",
            subject_template_name="core/emails/password_reset_subject.txt",
            success_url="/senha/email-enviado/",
        ),
        name="password_reset",
    ),
    path(
        "senha/email-enviado/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="core/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "senha/redefinir/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="core/password_reset_confirm.html",
            success_url="/senha/concluida/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "senha/concluida/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="core/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("primeiro-acesso/", views.primeiro_acesso, name="primeiro_acesso"),
    path(
        "certificados/validar/",
        views.validar_certificado,
        name="validar_certificado",
    ),
    path(
        "certificados/<str:codigo>/",
        views.validar_certificado,
        name="validar_certificado_codigo",
    ),
    path(
        "certificados/<str:codigo>/imprimir/",
        views.certificado_imprimir,
        name="certificado_imprimir",
    ),
    path(
        "relatorios/treinamentos/",
        views.relatorio_treinamentos,
        name="relatorio_treinamentos",
    ),
    path(
        "liberacoes/lote/",
        views.liberar_curso_lote,
        name="liberar_curso_lote",
    ),
    path(
        "empresas/",
        views.empresas_operacionais,
        name="empresas_operacionais",
    ),
    path(
        "empresas/<int:empresa_id>/editar/",
        views.editar_empresa_operacional,
        name="editar_empresa_operacional",
    ),
    path(
        "empresas/<int:empresa_id>/alternar/",
        views.alternar_empresa_operacional,
        name="alternar_empresa_operacional",
    ),
    path(
        "tecnicos/",
        views.tecnicos_operacionais,
        name="tecnicos_operacionais",
    ),
    path(
        "tecnicos/<int:tecnico_id>/editar/",
        views.editar_tecnico_operacional,
        name="editar_tecnico_operacional",
    ),
    path(
        "tecnicos/<int:tecnico_id>/alternar/",
        views.alternar_tecnico_operacional,
        name="alternar_tecnico_operacional",
    ),
    path(
        "responsaveis/",
        views.responsaveis_empresas,
        name="responsaveis_empresas",
    ),
    path(
        "responsaveis/<int:responsavel_id>/editar/",
        views.editar_responsavel_empresa,
        name="editar_responsavel_empresa",
    ),
    path(
        "responsaveis/<int:responsavel_id>/alternar/",
        views.alternar_responsavel_empresa,
        name="alternar_responsavel_empresa",
    ),
    path(
        "produtos/<int:produto_id>/cursos/",
        views.cursos_por_produto,
        name="cursos_por_produto",
    ),
    path("cursos/<int:curso_id>/", views.curso_detalhe, name="curso_detalhe"),
    path(
        "cursos/<int:curso_id>/etapas/<int:etapa_id>/",
        views.curso_detalhe,
        name="curso_etapa",
    ),
]
