from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("saude/", views.saude, name="saude"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="core/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "senha/esqueci/",
        auth_views.PasswordResetView.as_view(
            template_name="core/password_reset_form.html",
            email_template_name="core/emails/password_reset_email.txt",
            subject_template_name="core/emails/password_reset_subject.txt",
            success_url="/senha/email-enviado/",
        ),
        name="password_reset",
    ),
    path(
        "senha/email-enviado/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="core/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "senha/redefinir/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="core/password_reset_confirm.html",
            success_url="/senha/concluida/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "senha/concluida/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="core/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("primeiro-acesso/", views.primeiro_acesso, name="primeiro_acesso"),
    path(
        "certificados/validar/",
        views.validar_certificado,
        name="validar_certificado",
    ),
    path(
        "certificados/<str:codigo>/",
        views.validar_certificado,
        name="validar_certificado_codigo",
    ),
    path(
        "certificados/<str:codigo>/imprimir/",
        views.certificado_imprimir,
        name="certificado_imprimir",
    ),
    path(
        "relatorios/treinamentos/",
        views.relatorio_treinamentos,
        name="relatorio_treinamentos",
    ),
    path(
        "relatorios/treinamentos/exportar/",
        views.exportar_relatorio_treinamentos,
        name="exportar_relatorio_treinamentos",
    ),
    path(
        "historico/",
        views.historico_operacional,
        name="historico_operacional",
    ),
    path(
        "liberacoes/lote/",
        views.liberar_curso_lote,
        name="liberar_curso_lote",
    ),
    path(
        "liberacoes/importar/",
        views.importar_liberacoes_operacionais,
        name="importar_liberacoes_operacionais",
    ),
    path(
        "empresas/",
        views.empresas_operacionais,
        name="empresas_operacionais",
    ),
    path(
        "empresas/<int:empresa_id>/editar/",
        views.editar_empresa_operacional,
        name="editar_empresa_operacional",
    ),
    path(
        "empresas/<int:empresa_id>/acessar/",
        views.acessar_empresa_operacional,
        name="acessar_empresa_operacional",
    ),
    path(
        "empresas/<int:empresa_id>/painel/",
        views.painel_empresa_operacional,
        name="painel_empresa_operacional",
    ),
    path(
        "empresas/<int:empresa_id>/alternar/",
        views.alternar_empresa_operacional,
        name="alternar_empresa_operacional",
    ),
    path(
        "empresas/<int:empresa_id>/excluir/",
        views.excluir_empresa_operacional,
        name="excluir_empresa_operacional",
    ),
    path(
        "tecnicos/",
        views.tecnicos_operacionais,
        name="tecnicos_operacionais",
    ),
    path(
        "tecnicos/importar/",
        views.importar_tecnicos_operacionais,
        name="importar_tecnicos_operacionais",
    ),
    path(
        "tecnicos/<int:tecnico_id>/editar/",
        views.editar_tecnico_operacional,
        name="editar_tecnico_operacional",
    ),
    path(
        "tecnicos/<int:tecnico_id>/alternar/",
        views.alternar_tecnico_operacional,
        name="alternar_tecnico_operacional",
    ),
    path(
        "catalogo/produtos/",
        views.produtos_operacionais,
        name="produtos_operacionais",
    ),
    path(
        "catalogo/produtos/<int:produto_id>/editar/",
        views.editar_produto_operacional,
        name="editar_produto_operacional",
    ),
    path(
        "catalogo/produtos/<int:produto_id>/alternar/",
        views.alternar_produto_operacional,
        name="alternar_produto_operacional",
    ),
    path(
        "catalogo/cursos/",
        views.cursos_operacionais,
        name="cursos_operacionais",
    ),
    path(
        "catalogo/cursos/<int:curso_id>/editar/",
        views.editar_curso_operacional,
        name="editar_curso_operacional",
    ),
    path(
        "catalogo/cursos/<int:curso_id>/alternar/",
        views.alternar_curso_operacional,
        name="alternar_curso_operacional",
    ),
    path(
        "catalogo/cursos/<int:curso_id>/conteudo/",
        views.conteudo_curso_operacional,
        name="conteudo_curso_operacional",
    ),
    path(
        "catalogo/cursos/<int:curso_id>/etapas/criar/",
        views.criar_etapa_operacional,
        name="criar_etapa_operacional",
    ),
    path(
        "catalogo/etapas/<int:etapa_id>/editar/",
        views.editar_etapa_operacional,
        name="editar_etapa_operacional",
    ),
    path(
        "catalogo/etapas/<int:etapa_id>/alternar/",
        views.alternar_etapa_operacional,
        name="alternar_etapa_operacional",
    ),
    path(
        "catalogo/etapas/<int:etapa_id>/questoes/criar/",
        views.criar_questao_operacional,
        name="criar_questao_operacional",
    ),
    path(
        "catalogo/questoes/<int:questao_id>/editar/",
        views.editar_questao_operacional,
        name="editar_questao_operacional",
    ),
    path(
        "catalogo/questoes/<int:questao_id>/excluir/",
        views.excluir_questao_operacional,
        name="excluir_questao_operacional",
    ),
    path(
        "catalogo/questoes/<int:questao_id>/alternativas/criar/",
        views.criar_alternativa_operacional,
        name="criar_alternativa_operacional",
    ),
    path(
        "catalogo/alternativas/<int:alternativa_id>/editar/",
        views.editar_alternativa_operacional,
        name="editar_alternativa_operacional",
    ),
    path(
        "catalogo/alternativas/<int:alternativa_id>/excluir/",
        views.excluir_alternativa_operacional,
        name="excluir_alternativa_operacional",
    ),
    path(
        "responsaveis/",
        views.responsaveis_empresas,
        name="responsaveis_empresas",
    ),
    path(
        "responsaveis/<int:responsavel_id>/editar/",
        views.editar_responsavel_empresa,
        name="editar_responsavel_empresa",
    ),
    path(
        "responsaveis/<int:responsavel_id>/alternar/",
        views.alternar_responsavel_empresa,
        name="alternar_responsavel_empresa",
    ),
    path(
        "responsaveis/<int:responsavel_id>/convite/",
        views.reenviar_convite_responsavel,
        name="reenviar_convite_responsavel",
    ),
    path(
        "produtos/<int:produto_id>/cursos/",
        views.cursos_por_produto,
        name="cursos_por_produto",
    ),
    path("cursos/<int:curso_id>/", views.curso_detalhe, name="curso_detalhe"),
    path(
        "cursos/<int:curso_id>/etapas/<int:etapa_id>/",
        views.curso_detalhe,
        name="curso_etapa",
    ),
]
